### ISSUE TITLE
Moving/resizing features with arrow keys also moves visible segment when zoomed in.

### ISSUE THREAD

**Issue by iFreilicht** [cvhciKIT/sloth#123] opened 2017-04-07 10:23 UTC
To replicate:
 
1. Open a file at least 200x200 pixels large
2. Place any kind of feature
3. Zoom in as far as you can
4. Press ESC and left-click the feature once to select it
5. Press the Arrow Keys (+Shift and +Ctrl allowed) to move/resize the feature. This will move the visible segment of the image as well as the feature.

I'm on Ubuntu 14.04 LTS in case that's important.

**Comment by nilsonholger** [comment] 2017-06-02 10:35
Hey @iFreilicht, sounds weird. Is this similar or a duplicate of #113?

**Comment by iFreilicht** [comment] 2017-06-04 15:29
No, not at all. Try the steps I outlined above to see for yourself.

**Comment by nilsonholger** [comment] 2017-06-08 13:12
Sorry, but I can't reproduce this issue (tested on Ubuntu 16.04.2 LTS as well as macOS 10.12.5), for me only the label is changed in size and position. Can anybody reproduce this issue? Right now, I would assume it's related to the GUI toolkit used for 14.04, so I'm leaning towards closing this issue as a "can't fix"!

**Comment by iFreilicht** [comment] 2017-06-08 13:34
This might very well be the case. Unfortunately, I am not able to upgrade to 16.04.

**Comment by nilsonholger** [comment] 2017-06-08 15:35
Sorry to hear that, I will close this for now until somebody confirms this on other platforms/versions.

**Closed by nilsonholger** 2017-06-08 15:35 UTC
