### ISSUE TITLE
Is it possible to make Sloth display the class name and other extra text on top of bounding box?

### ISSUE THREAD

**Issue by jrao1** [cvhciKIT/sloth#120] opened 2017-03-19 04:14 UTC
For example if I added a "name" property at the same level as "width"/"height"/"x"/"y", is there a way to let this name show up on top of the bounding box?

**Comment by iFreilicht** [comment] 2017-04-07 10:17
See #100.

**Comment by nilsonholger** [comment] 2017-06-02 10:33
As @iFreilicht noted, duplicate of #100, closed.

**Closed by nilsonholger** 2017-06-02 10:33 UTC
