### ISSUE TITLE
Sloth does not go to previously opened file path when File|Open selected.

### ISSUE THREAD

**Issue by isaacgerg** [cvhciKIT/sloth#104] opened 2016-09-26 19:14 UTC

**Comment by nilsonholger** [comment] 2016-10-14 14:44
Well, it does so OSX when doing an "Open existing annotation file", but it doesn't for the "Add an image" button (it ALWAYS starts at the current running directory), so I really can't reproduce your problem. Also, as this functionality seems to be OS dependent, I would not want to include such a mechanism "per OS", that would make the code quite messy. So sorry, but that's a "can't/won't fix"!

**Closed by nilsonholger** 2016-10-14 14:44 UTC
