### ISSUE TITLE
can't start sloth

### ISSUE THREAD

**Issue by RunshengSong** [cvhciKIT/sloth#92] opened 2015-09-18 19:13 UTC
Hi,

I think I have installed all prerequisite packages but when I try to start sloth in bash it gives me this:

E:\Programs\Anaconda\python.exe: can't open file '/cygdrive/e/Programs/Anaconda/Scripts/sloth': [Errno 2] No such file or directory

thanks for any suggestions

**Comment by alexbra** [comment] 2015-09-22 21:21
I have the similar problem. I can't run sloth in command prompt. I use Anaconda and Pyhton 2.7. 
Thanks for answer

**Comment by jskye** [comment] 2015-10-19 10:30
sloth: command not found

**Comment by jskye** [comment] 2015-10-19 10:31
python sloth
/usr/local/opt/python/bin/python2.7: can't find '__main__' module in 'sloth'

**Comment by oolongtea** [comment] 2015-12-02 23:57
One thing to check is that your `PYTHONPATH` is pointing to the root of the sloth repository. As an example, I did:

`$ export PYTHONPATH=/home/user/github_repos/sloth:$PYTHONPATH`

then I could run sloth like this:

`$ sloth`

which eventually is calling the file `sloth/bin/sloth`.

**Comment by debpol** [comment] 2016-01-04 16:33
Hi!
I have the same issue. I can´t start sloth, I tried following the first step. http://sloth.readthedocs.org/en/latest/first_steps.html

I´m new in python, and I´m working whit windows 7, python 2.7. I´ve installed sloth in C:\Python27\Lib\site-packages\sloth\bin, and PyQt4 C:\Python27\Lib\site-packages\PyQt4.
All versions for x64. And I´ve intalled PIL too.

I added in my environment varibles PYTHONPATH 
C:\Python27\Lib\site-packages\sloth\bin;

Now, I tried to run from command line (cmd): 
C:\sloth C:\sloth-master\examples\example1_labels.json

But, I have got error message : "sloth" It is not recognized as an internal or external command, operable program or batch file

I'm not sure if I forgot to any previous step or whats I´m doing wrong? 
Any help is welcome! Thanks a lot!

**Comment by alexbra** [comment] 2016-01-04 16:41
I've install Ubuntu. I couldn't solve this problem in Windows

**Comment by debpol** [comment] 2016-01-04 17:00
auch! X(  
it not sound good, but, yes, I think I have to do it sooner or later.
Thanks alexbra!

**Comment by bhushi3890** [comment] 2016-02-12 22:27
prep-end it with "python". So new command will look like this :
python sloth examples/example1_labels.json

**Comment by gosftw** [comment] 2016-06-26 00:26
`/usr/bin/python: symbol lookup error: /usr/local/lib/libQt5DBus.so.5: undefined symbol: _Z28qEnvironmentVariableIntValuePKcPb
`
Any idea to fix this?

**Comment by nilsonholger** [comment] 2016-07-30 00:21
@gosftw Sorry, but this seems to be a problem with your ElementaryOS installation, and not really with sloth. Information on that specific missing symbol is quite sparse, but my hunch right now would be that there is a mismatch between your installed python and QT versions.

@RunshengSong @alexbra Sorry for your trouble, but internally we only use Linux/OSX, no Windows, so we can't really reproduce your problems. Under normal circumstances, it should run just fine on Windows, too, but I suppose that's assuming a standard Python/QT installation. I don't have the slightest idea what kind of problems using Anaconda might create.

@debpol Pretty much what @bhushi3890 said, call it using `python sloth`. Just because you install this into python's path does not mean that Windows will find a sloth command (as your error message states).

If anybody here is sufficiently happy with these answers I would like to close this issue!

**Closed** 2016-08-03 20:26 UTC

**Comment by tanayz** [comment] 2016-12-26 18:31
For me in windows it works in the following way
```
git clone https://github.com/cvhciKIT/sloth.git
cd sloth
python setup.py install
python sloth/bin/sloth examples/example1_labels.json
```
